apiVersion: v1
kind: Service
metadata:
  name: {{ include "netcore3webapprazor.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
 #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
{{ include "netcore3webapprazor.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "netcore3webapprazor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
